apiVersion: v1
kind: Service
metadata:
  name: tradevault-api
  namespace: tradevault
  labels:
    app: tradevault-api
spec:
  type: NodePort
  selector:
    app: tradevault-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP