apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tradevault-api
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - tradevault
  selector:
    matchLabels:
      app: tradevault-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s