apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: tradevault-test-alert
  namespace: monitoring
  labels:
    release: monitoring

spec:
  groups:
    - name: tradevault-test
      rules:
      - alert: TradeVaultTestAlert
        expr: vector(1)
        for: 1m
        labels:
          severity: warning
          app: devops-app
        annotations:
          summary: TradeVault test alert
          description: Testing Slack integration