apiVersion: v1
kind: Service
metadata:
  name: tradevault-api
  namespace: tradevault
spec:
  type: ClusterIP
  selector:
    app: tradevault-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000