apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tradevault-rds-secret
  namespace: tradevault
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: tradevault-secret-store
    kind: ClusterSecretStore

  target:
    name: tradevault-secret
    creationPolicy: Owner

  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: tradevault/dev/rds
        property: POSTGRES_USER

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: tradevault/dev/rds
        property: POSTGRES_PASSWORD